## global parameters: These will be used in multiple locations

# frames
/calibration_params/imu_frame: "imu_link"
/calibration_params/lidar_frame: "lidar_h_link"
/calibration_params/camera_frame: "F1_link"
/calibration_params/world_frame: "world"
/calibration_params/baselink_frame: "imu_link"

# topic frequencies
/calibration_params/imu_hz: 200
/calibration_params/camera_hz: 10
/calibration_params/lidar_hz: 10

# calibrations
/calibration_params/static_extrinsics: true
/calibration_params/camera_intrinsics_path: "ig3/cam.json"
/calibration_params/imu_intrinsics_path: "ig3/imu.json"
