# optimization params
optimization_period: 0.07
lag_duration: 10
pseudo_marginalization: true
information_weights_config: '/optimization/lio_information_weights.json'

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_NORMAL_CHOLESKY'
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 10
  max_solver_time_in_seconds: 0.05
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

sensor_models:
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'lidar_odometry'
    type: 'bs_models::LidarOdometry'
  - name: 'graph_publisher'
    type: 'bs_models::GraphPublisher'

slam_initialization:
  imu_topic: "/alphasense/imu"
  lidar_topic: "/hesai/pandar"
  init_mode: "LIDAR"
  max_optimization_s: 1.0
  min_trajectory_length_m: 3.0
  min_visual_parallax: 40.0
  inertial_information_weight: 0.01
  lidar_information_weight: 100.0
  vo_config: "examples/hilti_2023/vo/vo_params_init.json"
  matcher_config: 'examples/hilti_2023/matchers/loam_pandar32.json' # lidar specific
  output_folder: "" #"/userhome/results/init_results"

inertial_odometry:
  imu_topic: "/alphasense/imu"
  inertial_information_weight: 1


lidar_odometry:
  registration_config: 'examples/hilti_2023/registration/scan_to_map.json'
  matcher_config: 'examples/hilti_2023/matchers/loam_pandar32.json'
  lidar_type: 'VELODYNE'
  trigger_inertial_odom_constraints: true
  input_filters_config:  '' # 'lidar_filters/input_filters.json'
  input_topic: '/hesai/pandar'
  output_loam_points: true
  output_lidar_points: true
  publish_registration_map: true
  lidar_information_weight: 100.0
  frame_initializer_config: "examples/hilti_2023/frame_initializers/io.json"
  scan_output_directory: "" #'/userhome/data/2021_10_27_16_21_54_ConestogoBridge/debug'

  # these are only relevant if scan_output_directory is not empty
  save_graph_updates: true
  save_marginalized_scans: true
  save_scan_registration_results: true
