sensor_models:
  - name: 'camera'
    type: 'beam_models::camera_to_camera::VisualInertialOdom'
    motion_models: ['unicycle_3d']
  - name: 'ignition2d'
    type: 'fuse_models::Unicycle2DIgnition'
    ignition: true

motion_models:
  - name: 'unicycle_3d'
    type: 'beam_models::motion::Unicycle3D'

#publishers:
  #- name: 'odom_pub'
  #  type: 'beam_publishers::Odometry3DPublisher'
  ##- name: 'path_pub'
   # type: 'beam_publishers::Path3DPublisher'

ignition2d:
  publish_on_startup: true
  initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  initial_sigma: [1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9]

solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_NORMAL_CHOLESKY"
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 50
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

optimization_frequency: 1
lag_duration: 20


unicycle_ignition:
  publish_on_startup: true

unicycle_3d:
  process_noise_diagonal: [1000, 1000, 1000,
                           1000, 1000, 1000,
                           1000, 1000, 1000,
                           1000, 1000, 1000,
                           1000, 1000, 1000]
  buffer_length: 100000

VIO:
  cam_intrinsics_path: "/home/jake/data/VIO/euroc/intrinsics.json"
  image_topic: "/cam0/image_raw"
  image_hz: 20
  imu_topic: "/imu0"
  window_size: 100
  robot_extrinsics: "/home/jake/data/euroc/LVI_data/extrinsics.json"
  # gryo noise, accel noise, gryo walk, accel walk
  imu_intrinsics: [1.6968e-04, 2.0000e-3 , 1.9393e-05, 3.0000e-3]

#path_pub:
  #frame_id: 'odom'

