# global parameters: These will be used in multiple locations
optimization_frequency: 15
imu_frame: 'IMU'
lidar_frame: 'velodyne'
camera_frame: 'camera'
static_extrinsics: true

sensor_models:
  - name: 'global_mapper'
    type: 'global_mapping::GlobalMapper'
    motion_models: ['unicycle_3d']

motion_models:
  - name: 'unicycle_3d'
    type: 'bs_models::motion::Unicycle3D'

publishers:
  - name: 'path_pub'
    type: 'bs_publishers::Path3DPublisher'

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_NORMAL_CHOLESKY'
  minimizer_progress_to_stdout: false
  num_threads: 4
  num_linear_solver_threads: 4
  max_num_iterations: 50
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000

global_mapper:
  global_mapper_config: ''
  output_path: '/home/nick/results/beam_slam/global_mapper/'
  save_submaps: true
  save_final_map: true
  save_trajectory_cloud: true
  save_local_mapper_trajectory: true
  save_local_mapper_maps: true
  
path_pub:
  frame_id: 'odom' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # I DONT THINK THIS IS USED. Default: map
  odom_frame_id: 'odom' # I DONT THINK THIS IS USED. Default: odom
  base_link_frame_id: 'base_link' # I DONT THINK THIS IS USED. Default: base_link
  base_link_output_frame_id: 'base_link' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'odom' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: 'global_mapper/optimized_odometry' # Output odometry topic
