# global parameters: These will be used in multiple locations
optimization_frequency: 1
lag_duration: 2
imu_frame: "imu"
lidar_frame: "velodyne"
camera_frame: "camera"
world_frame: "world"
baselink_frame: "camera"
static_extrinsics: true,
intrinsics_path: "/home/alex/robots/data/KAARTA/F_kaarta.json"

sensor_models:
  - name: 'scan_matcher_3d'
    type: 'beam_models::frame_to_frame::ScanMatcher3D'
    motion_models: ['unicycle_3d']

motion_models:
  - name: 'unicycle_3d'
    type: 'beam_models::motion::Unicycle3D'

publishers:
  - name: 'odom_pub'
    type: 'beam_publishers::Odometry3DPublisher'
  - name: 'path_pub'
    type: 'beam_publishers::Path3DPublisher'

solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_NORMAL_CHOLESKY"
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 50
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000

scan_matcher_3d:
  type: 'MAPLOAM' # Options: MULTIICP, MULTINDT, MULTIGICP, MULTILOAM, MAPLOAM (TODO: LIBPOINTMATCHER, TEASER)
  matcher_params_path: '/home/alex/catkin_ws/src/beam_slam/beam_slam_launch/config/matcher_config/loam_vlp16.json' # DEFAULT_PATH uses the appropriate config in beam_slam_launch/config/matcher_config/. Setting to empty will use the default params defined in the class
  registration_config_path: 'DEFAULT_PATH' # DEFAULT_PATH uses the appropriate config in beam_slam_launch/config/registration_config/. Setting to empty will use the default params defined in the class
  differential: false # Default: false
  queue_size: 10 # Subscriber queue size. Default: 10
  downsample_size: 0 # voxel size (m) for downsample filter. Default: 0.03. Set to 0 for no downsampling
  matcher_noise: 1e-9 # Sets all diagonals on the covariance matrix to this value. Can also specify matcher_noise_diagonal instead which takes priority. Default: 1e-9.
  topic: '/velodyne_points'
  frame_initializer_type: 'POSEFILE' # options: ODOMETRY, POSEFILE
  frame_initializer_info: '/home/alex/robots/data/KAARTA/2019-07-10-17-32-53/trajectory_2019-07-10-17-32-53.ply' # for ODOMETRY: topic, for POSEFILE: path
  scan_output_directory: '/home/alex/robots/results/beam_slam/scans/' # Outputs scans as PCD files IFF not empty

path_pub:
  frame_id: 'odom' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # I DONT THINK THIS IS USED. Default: map
  odom_frame_id: 'odom' # I DONT THINK THIS IS USED. Default: odom
  base_link_frame_id: 'base_link' # I DONT THINK THIS IS USED. Default: base_link
  base_link_output_frame_id: 'base_link' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'odom' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: 'fixed_lag_smoother/optimized_odometry' # Output odometry topic