sensor_models:
  - name: 'scan_matcher_3d'
    type: 'beam_models::frame_to_frame::ScanMatcher3D'
    motion_models: ['unicycle_3d']


motion_models:
  - name: 'unicycle_3d'
    type: 'beam_models::motion::Unicycle3D'

publishers:
  - name: 'odom_pub'
    type: 'beam_publishers::Odometry3DPublisher'
  - name: 'path_pub'
    type: 'beam_publishers::Path3DPublisher'

solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_NORMAL_CHOLESKY"
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 50
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

optimization_period: 0.25
lag_duration: 10

unicycle_3d:
  process_noise_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
  buffer_length: 10 # Default: 3

scan_matcher_3d:
  type: 'ICP' # Options: ICP, NDT, GICP (TODO: LIBPOINTMATCHER, TEASER, LOAM)
  differential: 'false' # Default: false
  queue_size: 10 # Subscriber queue size. Default: 10
  pointcloud_topic: '/kaarta/aggregates'
  pointcloud_frame: 'velodyne' # used to lookup extrinsic calibrations
  frame_initializer_type: 'ODOMETRY'
  frame_initializer_topic: '/integrated_to_init'
  num_neighbors: 3 # how many neighboring scans to register against
  matcher_params_path: '' # Defaults to params in libbeam 

path_pub:
  frame_id: 'odom' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: 'false' # Default: true
  predict_to_current_time: 'false' # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # I DONT THINK THIS IS USED. Default: map
  odom_frame_id: 'odom' # I DONT THINK THIS IS USED. Default: odom
  base_link_frame_id: 'base_link' # I DONT THINK THIS IS USED. Default: base_link
  base_link_output_frame_id: 'base_link' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'odom' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: 'fixed_lag_smoother/optimized_odometry' # Output odometry topic
