# optimization params
optimization_period: 0.1
lag_duration: 7

sensor_models:
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'lidar_deskewer'
    type: 'bs_models::LidarScanDeskewer'
  - name: 'lidar_odometry'
    type: 'bs_models::LidarOdometry'

motion_models:
  - name: 'unicycle_3d'
    type: 'bs_models::Unicycle3D'

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_SCHUR'
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 20
  max_solver_time_in_seconds: 0.08
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000

slam_initialization:
  visual_measurement_topic: ""
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_packets_unpacked"
  frame_initializer_config: ""
  init_mode: "LIDAR"
  max_optimization_s: 1.0
  max_container_size: 100
  min_parallax: 50.0
  min_trajectory_length_m: 1.5
  output_folder: "" #"/home/nick/data/2021_10_27_16_21_54_ConestogoBridge/debug/slam_init"


inertial_odometry:
  imu_topic: "/imu/data"
  constraint_odom_topic: "/local_mapper/lidar_odometry/odom/global2"

lidar_deskewer:
  input_topic: '/lidar_h/velodyne_packets_unpacked'
  lidar_type: 'VELODYNE'
  frame_initializer_config: "frame_initializers/io.json"

lidar_odometry:
  # Scan registration params
  local_registration_config: 'registration/scan_to_map_loam.json'
  local_matcher_config: 'matchers/loam_vlp16.json'
  global_matcher_config: 'registration/loam_vlp16.json'

  # general params
  lidar_type: 'VELODYNE'
  input_filters_config:  '' # 'lidar_filters/input_filters.json'
  input_topic: '/local_mapper/lidar_deskewer/points_undistorted'
  output_loam_points: true
  output_lidar_points: true
  publish_active_submap: true
  publish_local_map: true
  publish_registration_results: true
  # frame_initializer_config: 'frame_initializers/path.json'
  frame_initializer_config: "/frame_initializers/io.json"
  frame_initializer_prior_noise_diagonal: [0,0,0,0,0,0] #[0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001]
  reloc_request_period: 1
  scan_output_directory: "" #'/userhome/data/2021_10_27_16_21_54_ConestogoBridge/debug'
  # these are only relevant if scan_output_directory is not empty
  save_graph_updates: true
  save_marginalized_scans: true

path_pub:
  frame_id: 'world' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # Default: map
  odom_frame_id: 'world' # Default: odom
  base_link_frame_id: 'imu' # Default: base_link
  base_link_output_frame_id: 'imu' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'world' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: '/local_mapper/optimized_odometry' # Output odometry topic
