# optimization params
optimization_period: 0.07
lag_duration: 6

sensor_models:
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'lidar_deskewer'
    type: 'bs_models::LidarScanDeskewer'
  - name: 'lidar_odometry'
    type: 'bs_models::LidarOdometry'
  - name: 'graph_visualization'
    type: 'bs_models::GraphVisualization'
  - name: 'gravity_alignment'
    type: 'bs_models::GravityAlignment'
  # - name: 'odom_pub'
  #   type: 'bs_publishers::Odometry3DPublisher'
  # - name: 'path_pub'
  #   type: 'bs_publishers::Path3DPublisher'

publishers:
    - name: 'graph'
      type: 'fuse_publishers::SerializedPublisher'

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_NORMAL_CHOLESKY'
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 10
  max_solver_time_in_seconds: 0.08
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

slam_initialization:
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_points"
  init_mode: "LIDAR"
  max_optimization_s: 1.0
  min_trajectory_length_m: 2.0
  inertial_information_weight: 0.001
  lidar_information_weight: 1.0
  max_triangulation_distance: 50.0 # vision specific
  max_triangulation_reprojection: 30.0 # vision specific
  matcher_config: 'matchers/loam_vlp16_init.json' # lidar specific
  output_folder: "" # "/userhome/debug/slam_init"

inertial_odometry:
  imu_topic: "/imu/data"
  inertial_information_weight: 0.001

gravity_alignment:
  imu_topic: "/imu/data"
  constraint_odom_topic: "/local_mapper/lidar_odometry/odom/global"
  gravity_info_weight: 10

lidar_deskewer:
  input_topic: '/lidar_h/velodyne_points'
  lidar_type: 'VELODYNE'
  frame_initializer_config: "frame_initializers/io.json"

lidar_odometry:
  registration_config: 'registration/scan_to_map_loam.json'
  matcher_config: 'matchers/loam_vlp16.json'
  lidar_type: 'VELODYNE'
  trigger_inertial_odom_constraints: true
  input_filters_config:  '' # 'lidar_filters/input_filters.json'
  input_topic: '/local_mapper/lidar_deskewer/points_undistorted'
  output_loam_points: true
  output_lidar_points: true
  publish_active_submap: true
  publish_registration_map: true
  publish_registration_results: true
  lidar_information_weight: 1000.0
  frame_initializer_config: "/frame_initializers/io.json"
  scan_output_directory: "" #'/userhome/data/2021_10_27_16_21_54_ConestogoBridge/debug'

  # these are only relevant if scan_output_directory is not empty
  save_graph_updates: true
  save_marginalized_scans: true
  save_scan_registration_results: true

path_pub:
  frame_id: 'world' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # Default: map
  odom_frame_id: 'world' # Default: odom
  base_link_frame_id: 'imu_link' # Default: base_link
  base_link_output_frame_id: 'imu_link' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'world' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: '/local_mapper/optimized_odometry' # Output odometry topic
