## global parameters: These will be used in multiple locations

# optimization params
optimization_frequency: 1
lag_duration: 2

# frames
imu_frame: "imu_ouster"
lidar_frame: "ouster"
camera_frame: "camera0"

# calibrations
static_extrinsics: true,
camera_intrinsics_path: "/home/nick/catkin_ws/src/beam_slam/calibrations/newercollege/camera0.json"
imu_intrinsics_path: "/home/nick/catkin_ws/src/beam_slam/calibrations/newercollege/imu_ouster.json"

sensor_models:
  - name: 'lio_initializer'
    type: 'beam_models::frame_to_frame::LioInitializer'


lio_initializer:
  matcher_params_path: '/home/nick/catkin_ws/src/beam_slam/config/matcher_config/loam_ouster64.json' # DEFAULT_PATH uses the appropriate config in beam_slam_launch/config/matcher_config/. Setting to empty will use the default params defined in the class
  registration_config_path: 'DEFAULT_PATH' # DEFAULT_PATH uses the appropriate config in beam_slam_launch/config/registration_config/. Setting to empty will use the default params defined in the class
  differential: false # Default: false
  matcher_noise: 1e-9 # Sets all diagonals on the covariance matrix to this value. Can also specify matcher_noise_diagonal instead which takes priority. Default: 1e-9.
  lidar_topic: '/os1_cloud_node/points'
  imu_topic: '/os1_cloud_node/imu'
  output_topic: 'lio_initialiser_result'
  nominal_gravity_direction: '-Y'
  undistort_scans: true
  aggregation_time: 0.1
  trajectory_time_window: 10
  min_trajectory_distance: 3
  outlier_threshold_t_m: 0.3
  outlier_threshold_r_deg: 15
  scan_output_directory: '/home/nick/results/beam_slam/lio_initializer/' # Outputs scans as PCD files IFF not empty

