# global parameters: These will be used in multiple locations
optimization_frequency: 1
lag_duration: 2
imu_frame: "IMU"
lidar_frame: "velodyne"
camera_frame: "camera"
static_extrinsics: true,
intrinsics_path: "/home/nick/config/calibrations/F_kaarta.json"

sensor_models:
  - name: 'lio_initializer'
    type: 'beam_models::frame_to_frame::LioInitializer'
    motion_models: ['unicycle_3d']

motion_models:
  - name: 'unicycle_3d'
    type: 'beam_models::motion::Unicycle3D'

solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_NORMAL_CHOLESKY"
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 50
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000

lio_initializer:
  matcher_params_path: 'DEFAULT_PATH' # DEFAULT_PATH uses the appropriate config in beam_slam_launch/config/matcher_config/. Setting to empty will use the default params defined in the class
  registration_config_path: 'DEFAULT_PATH' # DEFAULT_PATH uses the appropriate config in beam_slam_launch/config/registration_config/. Setting to empty will use the default params defined in the class
  differential: false # Default: false
  matcher_noise: 1e-9 # Sets all diagonals on the covariance matrix to this value. Can also specify matcher_noise_diagonal instead which takes priority. Default: 1e-9.
  lidar_topic: '/velodyne_points'
  imu_topic: '/imu/data'
  aggregation_time: 0.1
  trajectory_time_window: 
  min_trajectory_distance: 3
  outlier_threshold_t_m: 0.3
  outlier_threshold_r_deg: 15
  scan_output_directory: '/home/nick/results/beam_slam/lio_initializer/' # Outputs scans as PCD files IFF not empty

