optimization_period: 0.5
lag_duration: 10

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_SCHUR'
  minimizer_progress_to_stdout: true
  num_threads: 8
  num_linear_solver_threads: 8
  max_num_iterations: 8
  max_solver_time_in_seconds: 0.5
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

sensor_models:
  - name: 'visual_feature_tracker'
    type: 'bs_models::VisualFeatureTracker'
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'visual_odometry'
    type: 'bs_models::VisualOdometry'
  
motion_models:
  - name: 'unicycle_3d'
    type: 'bs_models::Unicycle3D'

# publishers:
#   - name: 'odom_pub'
#     type: 'bs_publishers::Odometry3DPublisher'
#   - name: 'path_pub'
#     type: 'bs_publishers::Path3DPublisher'

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000

visual_feature_tracker:
  image_topic: '/F1/image_raw'
  descriptor_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vo/orb_descriptor.json'
  detector_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vo/fastssc_detector.json'
  tracker_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vo/tracker.json'
  save_tracks_folder: ""

slam_initialization:
  visual_measurement_topic: "/local_mapper/visual_feature_tracker/visual_measurements"
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_points"
  frame_initializer_config: ""
  init_mode: "LIDAR"
  max_optimization_s: 0.0
  max_container_size: 100
  min_parallax: 50.0
  min_trajectory_length_m: 1.0
  reprojection_covariance_weight: 0.01
  reprojection_loss/type: "HUBER"
  reprojection_loss/a: 0.2
  output_folder: ""

inertial_odometry:
  imu_topic: "/imu/data"
  constraint_odom_topic: "/local_mapper/visual_odometry/odom/relative"

visual_odometry:
  visual_measurement_topic: "/local_mapper/visual_feature_tracker/visual_measurements"
  max_container_size: 300
  frame_initializer_config: "/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/frame_initializers/io.json"
  frame_initializer_prior_noise_diagonal: [0,0,0,0,0,0]
  use_pose_priors: false
  reloc_request_period: 3.0
  use_parallax: false
  keyframe_parallax: 10.0
  keyframe_translation_m: 1.0
  keyframe_rotation_deg: 20.0
  keyframe_max_duration: 2.5
  reprojection_covariance_weight: 0.01
  reprojection_loss/type: "HUBER"
  reprojection_loss/a: 0.2

lidar_odometry:
  # Local scan registration
  local_registration_type: 'MAPLOAM'
  local_registration_config_path: 'DEFAULT_PATH'
  local_matcher_params_path: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/matchers/loam_vlp16.json'
  local_registration_noise_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  # global scan registration
  global_registration_type: 'LOAM'
  global_matcher_params_path: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/matchers/loam_vlp16.json'
  global_registration_noise_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  # general params
  lidar_type: 'VELODYNE'
  input_filters_config_path: 'DEFAULT_PATH'
  input_topic: '/local_mapper/lidar_aggregation/points_undistorted'
  output_loam_points: true
  output_lidar_points: true
  publish_active_submap: true
  publish_local_map: true
  publish_registration_results: true
  frame_initializer_config: 'userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/frame_initializers/io.json'
  frame_initializer_prior_noise_diagonal: [0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001]
  reloc_request_period: 1
  scan_output_directory: ''

path_pub:
  frame_id: 'world' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # Default: map
  odom_frame_id: 'world' # Default: odom
  base_link_frame_id: 'imu' # Default: base_link
  base_link_output_frame_id: 'imu' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'world' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: '/local_mapper/optimized_odometry' # Output odometry topic