# optimization params
optimization_period: 0.07
lag_duration: 10
pseudo_marginalization: false

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_NORMAL_CHOLESKY'
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 10
  max_solver_time_in_seconds: 0.05
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

sensor_models:
  - name: 'visual_feature_tracker'
    type: 'bs_models::VisualFeatureTracker'
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'visual_odometry'
    type: 'bs_models::VisualOdometry'
  - name: 'lidar_deskewer'
    type: 'bs_models::LidarScanDeskewer'
  - name: 'lidar_odometry'
    type: 'bs_models::LidarOdometry'
  - name: 'graph_visualization'
    type: 'bs_models::GraphVisualization'
  # - name: 'gravity_alignment'
  #   type: 'bs_models::GravityAlignment'

publishers:
  - name: 'path_publisher'
    type: 'bs_publishers::Path3DPublisher'

visual_feature_tracker:
  image_topic: '/F1/image'
  descriptor_config: 'vo/orb_descriptor.json'
  detector_config: 'vo/fastssc_detector.json'
  tracker_config: 'vo/tracker.json'

slam_initialization:
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_points"
  init_mode: "LIDAR"
  max_optimization_s: 1.0
  min_trajectory_length_m: 3.0
  min_visual_parallax: 40.0
  inertial_information_weight: 1.0
  lidar_information_weight: 100.0
  vo_config: "vo/vo_params_init.json"
  matcher_config: 'matchers/loam_vlp16.json' # lidar specific
  output_folder: "" #"/userhome/results/init_results"

inertial_odometry:
  imu_topic: "/imu/data"
  inertial_information_weight: 1.0

visual_odometry:
  vo_config: "vo/vo_params.json"
  frame_initializer_config: "frame_initializers/io.json"
  keyframe_parallax: 25.0
  trigger_inertial_odom_constraints: true
  use_standalone_vo: true
  odom_information_weight: 100.0

gravity_alignment:
  imu_topic: "/imu/data"
  constraint_odom_topic: "/local_mapper/lidar_odometry/odometry"
  gravity_information_weight: 10.0

lidar_deskewer:
  input_topic: '/lidar_h/velodyne_points'
  lidar_type: 'VELODYNE'
  frame_initializer_config: "frame_initializers/io.json"

lidar_odometry:
  registration_config: 'registration/scan_to_map.json'
  matcher_config: 'matchers/loam_vlp16.json'
  lidar_type: 'VELODYNE'
  trigger_inertial_odom_constraints: true
  input_filters_config:  '' # 'lidar_filters/input_filters.json'
  input_topic: '/local_mapper/lidar_deskewer/points_undistorted'
  output_loam_points: true
  output_lidar_points: true
  publish_registration_map: false
  publish_registration_results: false
  lidar_information_weight: 100.0
  frame_initializer_config: "/frame_initializers/io.json"
  scan_output_directory: "" #'/userhome/data/2021_10_27_16_21_54_ConestogoBridge/debug'

  # these are only relevant if scan_output_directory is not empty
  save_graph_updates: true
  save_marginalized_scans: true
  save_scan_registration_results: true

path_publisher:
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array
