optimization_period: 0.07
lag_duration: 6

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_NORMAL_CHOLESKY'
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 10
  max_solver_time_in_seconds: 0.08
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

sensor_models:
  - name: 'visual_feature_tracker'
    type: 'bs_models::VisualFeatureTracker'
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'visual_odometry'
    type: 'bs_models::VisualOdometry'
  - name: 'lidar_deskewer'
    type: 'bs_models::LidarScanDeskewer'
  - name: 'lidar_odometry'
    type: 'bs_models::LidarOdometry'
  - name: 'gravity_alignment'
    type: 'bs_models::GravityAlignment'
  - name: 'graph_visualization'
    type: 'bs_models::GraphVisualization'

# publishers:
#     - name: 'graph'
#       type: 'fuse_publishers::SerializedPublisher'
#   - name: 'odom_pub'
#     type: 'bs_publishers::Odometry3DPublisher'
#   - name: 'path_pub'
#     type: 'bs_publishers::Path3DPublisher'


visual_feature_tracker:
  image_topic: '/F1/image'
  descriptor_config: 'vo/orb_descriptor.json'
  detector_config: 'vo/fastssc_detector.json'
  tracker_config: 'vo/tracker.json'

slam_initialization:
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_points"
  init_mode: "LIDAR"
  max_optimization_s: 1.0
  min_trajectory_length_m: 2.0
  min_visual_parallax: 40.0
  reprojection_information_weight: 1.0
  inertial_information_weight: 0.001
  lidar_information_weight: 10.0
  matcher_config: 'matchers/loam_vlp16_init.json' # lidar specific
  output_folder: "" #"/home/nick/debug/slam_init"

inertial_odometry:
  imu_topic: "/imu/data"
  inertial_information_weight: 0.001

visual_odometry:
  frame_initializer_config: "frame_initializers/io.json"
  reloc_request_period: 3.0
  keyframe_parallax: 20.0
  reprojection_information_weight: 1.0
  trigger_inertial_odom_constraints: true

gravity_alignment:
  imu_topic: "/imu/data"
  constraint_odom_topic: "/local_mapper/lidar_odometry/odom/global"
  inertial_information_weight: 10

lidar_deskewer:
  input_topic: '/lidar_h/velodyne_points'
  lidar_type: 'VELODYNE'
  frame_initializer_config: "frame_initializers/io.json"

lidar_odometry:
  registration_config: 'registration/scan_to_map_loam.json'
  matcher_config: 'matchers/loam_vlp16.json'
  lidar_type: 'VELODYNE'
  trigger_inertial_odom_constraints: true
  input_filters_config:  '' # 'lidar_filters/input_filters.json'
  input_topic: '/local_mapper/lidar_deskewer/points_undistorted'
  output_loam_points: true
  output_lidar_points: true
  publish_active_submap: true
  publish_registration_map: true
  publish_registration_results: true
  lidar_information_weight: 10.0
  frame_initializer_config: "/frame_initializers/io.json"
  scan_output_directory: "" #'/userhome/data/2021_10_27_16_21_54_ConestogoBridge/debug'

  # these are only relevant if scan_output_directory is not empty
  save_graph_updates: true
  save_marginalized_scans: true
  save_scan_registration_results: true
