optimization_period: 0.1
lag_duration: 7

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_NORMAL_CHOLESKY'
  minimizer_progress_to_stdout: true
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 10
  max_solver_time_in_seconds: 0.08
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015


sensor_models:
  - name: 'visual_feature_tracker'
    type: 'bs_models::VisualFeatureTracker'
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'visual_odometry'
    type: 'bs_models::VisualOdometry'

publishers:
    - name: 'graph'
      type: 'fuse_publishers::SerializedPublisher'
#   - name: 'odom_pub'
#     type: 'bs_publishers::Odometry3DPublisher'
#   - name: 'path_pub'
#     type: 'bs_publishers::Path3DPublisher'

visual_feature_tracker:
  image_topic: '/F1/image_raw_debayered'
  descriptor_config: 'vo/orb_descriptor.json'
  detector_config: 'vo/fastssc_detector.json'
  tracker_config: 'vo/tracker.json'
  publish_tracks: true

slam_initialization:
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_packets_unpacked"
  init_mode: "LIDAR"
  max_optimization_s: 1.0
  initialization_window_s: 2.0
  min_trajectory_length_m: 2.0
  reprojection_information_weight: 1.0
  inertial_information_weight: 1.0
  max_triangulation_distance: 50.0
  max_triangulation_reprojection: 30.0
  output_folder: ""

inertial_odometry:
  imu_topic: "/imu/data"
  constraint_odom_topic: "/local_mapper/visual_odometry/odometry"
  inertial_information_weight: 1.0

visual_odometry:
  max_container_size: 300
  frame_initializer_config: "frame_initializers/io.json"
  reloc_request_period: 3.0
  keyframe_parallax: 30.0
  keyframe_max_duration: 0.25
  reprojection_information_weight: 1.0
  max_triangulation_distance: 40.0
  max_triangulation_reprojection: 15.0

path_pub:
  frame_id: 'world' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # Default: map
  odom_frame_id: 'world' # Default: odom
  base_link_frame_id: 'imu' # Default: base_link
  base_link_output_frame_id: 'imu' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'world' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: '/local_mapper/optimized_odometry' # Output odometry topic
