# optimization params
optimization_period: 0.07
lag_duration: 7
pseudo_marginalization: false

solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_NORMAL_CHOLESKY'
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 10
  max_solver_time_in_seconds: 0.05
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

sensor_models:
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'visual_odometry'
    type: 'bs_models::VisualOdometry'
  - name: 'graph_visualization'
    type: 'bs_models::GraphVisualization'
  # - name: 'gravity_alignment'
  #   type: 'bs_models::GravityAlignment'

publishers:
  - name: 'path_publisher'
    type: 'bs_publishers::Path3DPublisher'

slam_initialization:
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_points"
  init_mode: "LIDAR"
  max_optimization_s: 1.0
  min_trajectory_length_m: 3.0
  min_visual_parallax: 40.0
  vo_config: "vo/vo_params_init.json"
  matcher_config: 'matchers/loam_vlp16.json' # lidar specific
  output_folder: "" #"/userhome/results/init_results"

inertial_odometry:
  imu_topic: "/imu/data"

visual_odometry:
  vo_config: "vo/vo_params.json"
  frame_initializer_config: "frame_initializers/io.json"
  keyframe_parallax: 25.0
  trigger_inertial_odom_constraints: true
  use_standalone_vo: true

gravity_alignment:
  imu_topic: "/imu/data"
  constraint_odom_topic: "/local_mapper/visual_odometry/odometry"

path_publisher:
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array
