## global parameters: These will be used in multiple locations

# frames
/calibration_params/imu_frame: "imu_link"
/calibration_params/lidar_frame: "dummy_lidar_link"
/calibration_params/camera_frame: "dummy_camera_link"
/calibration_params/world_frame: "world"
/calibration_params/baselink_frame: "imu_link"

# calibrations
/calibration_params/static_extrinsics: true
/calibration_params/imu_intrinsics_path: "/home/alex/catkin_ws/src/beam_slam/beam_slam_launch/calibrations/simulation/imu.json"
