# optimization params
optimization_period: 1
lag_duration: 10

# sensor models
sensor_models:
  - name: 'imu_3d'
    type: 'bs_models::Imu3D'

# motion models
motion_models:
  - name: 'unicycle_3d'
    type: 'bs_models::Unicycle3D'

# solver options
solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_NORMAL_CHOLESKY"
  minimizer_progress_to_stdout: true
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 15
  max_solver_time_in_seconds: 0.7
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000


imu_3d:
  input_topic: '/imu/raw'
  frame_initializer_type: 'POSEFILE' # Default: ODOMETRY
  frame_initializer_info: '/home/alex/catkin_ws/src/beam_slam/beam_slam_launch/simulation_bags/imu_simulation_ground_truth.ply' # Default: ""
  sensor_frame_id_override: 'imu_link' # Default: ""
  queue_size: 300 # Default: 300
  lag_duration: 1.0 # Default: 1.0
  key_frame_rate: 1.0 # Default: 1.0
  prior_noise: 1.0e-9 # Default: 1.0e-9
