## global parameters: These will be used in multiple locations

# frames
/calibration_params/imu_frame: "inertial_link"
/calibration_params/lidar_frame: "hvlp_link"
/calibration_params/camera_frame: "F1_link"
/calibration_params/world_frame: "world"
/calibration_params/baselink_frame: "inertial_link"

# calibrations
/calibration_params/static_extrinsics: true
/calibration_params/imu_intrinsics_path: "/userhome/catkin_ws/src/beam_slam/beam_slam_launch/calibrations/ig_simulation/imu.json"
