## global parameters: These will be used in multiple locations

# frames
/calibration_params/imu_frame: "imu"
/calibration_params/lidar_frame: "velodyne"
/calibration_params/camera_frame: "camera1"
/calibration_params/world_frame: "world"
/calibration_params/baselink_frame: "imu"

# calibrations
/calibration_params/static_extrinsics: true,
/calibration_params/camera_intrinsics_path: "/home/nick/catkin_ws/src/beam_slam/beam_slam_launch/calibrations/kaarta/camera.json"
/calibration_params/imu_intrinsics_path: "/home/nick/catkin_ws/src/beam_slam/beam_slam_launch/calibrations/kaarta/imu.json"
