## global parameters: These will be used in multiple locations

# frames
/calibration_params/imu_frame: "imu"
/calibration_params/lidar_frame: "lidar_horz"
/calibration_params/camera_frame: "camera_left"
/calibration_params/world_frame: "world"
/calibration_params/baselink_frame: "imu"

# calibrations
/calibration_params/static_extrinsics: true,
/calibration_params/camera_intrinsics_path: "/userhome/catkin_ws/src/beam_slam/calibrations/ntu/camera.json"
/calibration_params/imu_intrinsics_path: "/userhome/catkin_ws/src/beam_slam/calibrations/ntu/imu.json"
