odometry_topic: /odometry/ground_truth # used just for retrieving timing only
aggregation_time_topic: /aggregation_time # output topic for trigger
aggregation_time_seconds: 9 # period between time triggers
log_level: INFO # Options: DEBUG, INFO, WARN, ERROR, FATAL. Set ROS console 
                # log level.  Note this sets the system level and will 
                # override any other log_level set in other nodes

