## global parameters: These will be used in multiple locations

# frames
/calibration_params/imu_frame: "imu0"
/calibration_params/lidar_frame: "vicon"
/calibration_params/camera_frame: "cam0"
/calibration_params/world_frame: "world"
/calibration_params/baselink_frame: "imu0"

# calibrations
/calibration_params/static_extrinsics: true
/calibration_params/camera_intrinsics_path: "/home/jake/catkin_ws/src/beam_slam/beam_slam_launch/calibrations/euroc/camera.json"
/calibration_params/imu_intrinsics_path: "/home/jake/catkin_ws/src/beam_slam/beam_slam_launch/calibrations/euroc/imu.json"
