# optimization params
optimization_period: 1
lag_duration: 10

# sensor models
sensor_models:
  # - name: 'camera'
  #   type: 'bs_models::camera_to_camera::VisualInertialOdom'
  #   motion_models: ['unicycle_3d']
  #   ignition: true
  - name: 'gt_initializer'
    type: 'bs_models::frame_to_frame::GTInitializer'

# motion models
motion_models:
  - name: 'unicycle_3d'
    type: 'bs_models::motion::Unicycle3D'

# solver options
solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_NORMAL_CHOLESKY"
  minimizer_progress_to_stdout: true
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 15
  max_solver_time_in_seconds: 0.7
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000


camera:
  source: "VIO"
  image_topic: "/cam0/image_raw"
  imu_topic: "/imu0"
  reloc_topic: "/reloc_request"
  init_path_topic: "/lo_initialiser_result"
  frame_odometry_output_topic: "/vio_init"
  new_keyframes_topic: "/new_keyframes"
  slam_chunk_topic: "/slam_chunks"
  landmark_topic: "/landmarks"
  descriptor: "ORB"
  window_size: 150 # number of images to store landmark information for before clearing for new images
  num_features_to_track: 100 # number of features to track from image to image
  keyframe_window_size: 20 # number of keyframes to store before wiping for new images
  keyframe_parallax: 70 # if avg parallax to the previous keyframe exceeds this then set keyframe
  keyframe_tracks_drop: 150 # if number of visible landmarks in images drops below this then set keyframe
  keyframe_min_time_in_seconds: 0.5 # minimum amount of time between keyframes
  init_max_optimization_time_in_seconds: 1.0 # max amopunt of time to optimize the initializer map
  init_map_output_directory: "" # Outputs vio map into directory if not empty

gt_initializer:
  imu_topic: "/imu0"
  pose_file_path: "/home/jake/V1_01_poses.ply"
  trajectory_time_window: 5.0
  output_topic: "/lo_initialiser_result"
  min_trajectory_length: 0.5 # trajectory length to accept (in metres)