# optimization params
optimization_period: 0.2
lag_duration: 7

# sensor models
sensor_models:
  - name: 'vio'
    type: 'bs_models::VisualInertialOdometry'
    motion_models: ['unicycle_3d']
    ignition: true
  - name: 'gt_initializer'
    type: 'bs_models::GTInitializer'

# motion models
motion_models:
  - name: 'unicycle_3d'
    type: 'bs_models::Unicycle3D'

# publishers:
#   - name: 'odom_pub'
#     type: 'bs_publishers::Odometry3DPublisher'

# solver options
solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_SCHUR"
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 50
  max_solver_time_in_seconds: 0.08
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000


vio:
  source: 'VIO'
  image_topic: '/cam0/image_raw'
  imu_topic: '/imu0'
  init_path_topic: '/local_mapper/gt_initialiser/result'
  descriptor: 'BEBLID'
  descriptor_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/descriptor.json'
  detector: 'FAST'
  detector_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/fast_detector.json'
  tracker_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/tracker.json'
  tracker_window_size: 150 
  num_features_to_track: 100
  keyframe_window_size: 10 
  keyframe_min_time_in_seconds: 0.2 
  init_max_optimization_time_in_seconds: 1.0
  init_map_output_directory: '' 
  init_use_scale_estimate: false 

  gt_initializer:
  imu_topic: "/imu0"
  frame_initializer_type: 'PSOEFILE' 
  frame_initializer_info: '/home/jake/data/VIO/euroc/V1_01_poses.ply'
  frame_initializer_sensor_frame_id: 'imu0'
  trajectory_time_window: 5.0
  min_trajectory_length: 0.5 # trajectory length to accept (in metres)

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # I DONT THINK THIS IS USED. Default: map
  odom_frame_id: 'world' # I DONT THINK THIS IS USED. Default: odom
  base_link_frame_id: 'base_link' # I DONT THINK THIS IS USED. Default: base_link
  base_link_output_frame_id: 'imu0' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'world' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: '/local_mapper/optimized_odometry' # Output odometry topic