## Section 1 - Plugins to load
sensor_models:
  - name: 'imu2d'
    type: 'fuse_models::Imu2D'
    motion_models: ['unicycle2d']
  - name: 'odometry2d'
    type: 'fuse_models::Odometry2D'
    motion_models: ['unicycle2d']
  - name: 'ignition2d'
    type: 'fuse_models::Unicycle2DIgnition'
    ignition: true

motion_models:
  - name: 'unicycle2d'
    type: 'fuse_models::Unicycle2D'

publishers:
  - name: 'odometry2dpublisher'
    type: 'fuse_models::Odometry2DPublisher'
  - name: 'path2dpublisher'
    type: 'fuse_publishers::Path2DPublisher'


## Section 2 - Parameter Tuning
## Sensor Model Parameters
imu2d:
  angular_velocity_dimensions: ['yaw']
  linear_acceleration_dimensions: []
  orientation_dimensions: []
  differential: false
  disable_checks: false
  queue_size: 10
  throttle_period: 0.1
  remove_gravitational_acceleration: false
  gravitational_acceleration: 9.80665
  topic: '/imu/data'
  acceleration_target_frame: 'base_link'
  orientation_target_frame: 'base_link'
  twist_target_frame: 'base_link'

odometry2d:
  position_dimensions: []
  orientation_dimensions: []
  linear_velocity_dimensions: ['x']
  angular_velocity_dimensions: []
  differential: false
  disable_checks: false
  queue_size: 10
  throttle_period: 0.1
  topic: '/husky_velocity_controller/odom'
  twist_target_frame: 'base_link'
  pose_target_frame: 'odom'

ignition2d:
  publish_on_startup: true
  initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  initial_sigma: [1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9, 1.0e-9]

## Motion model parameters
unicycle2d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000
  velocity_norm_min: 1e-3

## Publisher parameters
odometry2dpublisher:
  topic: '/odometry/filtered_fuse'
  publish_tf: true
  predict_to_current_time: true
  predict_with_acceleration: false
  publish_frequency: 100
  scale_process_noise: false
  velocity_norm_min: 1e-3
  tf_cache_time: 10.0
  tf_timeout: 0.1
  queue_size: 1
  map_frame_id: 'map'
  odom_frame_id: 'odom'
  base_link_frame_id: 'base_link'
  base_link_output_frame_id: 'base_link'
  world_frame_id: 'odom'
  process_noise_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

path_pub:
  frame_id: 'odom'

## Section 3 - Optimization Parameters
optimization_frequency: 10.0
lag_duration: 3.0

solver_options:
  num_linear_solver_threads: 6
  num_threads: 6
