## global parameters: These will be used in multiple locations

# optimization params
optimization_frequency: 1

# frames
/calibration_params/imu_frame: "imu4"
/calibration_params/lidar_frame: "lidar" # set dummy lidar frame
/calibration_params/camera_frame: "camera" # set dummy camera frame
/calibration_params/world_frame: "world"
/calibration_params/baselink_frame: "imu4"

# calibrations
/calibration_params/static_extrinsics: true

## model plugins: declare all plugins to use and give a unique name

sensor_models:
  - name: 'imu_3d'
    type: 'bs_models::Imu3D'

## plugin params: specify all params for the plugins, using their unique name

solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_NORMAL_CHOLESKY"
  minimizer_progress_to_stdout: false
  num_threads: 2
  num_linear_solver_threads: 2
  max_num_iterations: 50
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

imu_3d:
  input_topic: '/imu0'
  frame_initializer_type: 'POSEFILE' # Default: ODOMETRY
  frame_initializer_info: '/home/alex/robots/data/Euroc/V1_01_poses.ply' # Default: ""
  sensor_frame_id_override: 'imu4' # Default: ""
  queue_size: 300 # Default: 300
  lag_duration: 1.0 # Default: 1.0
  key_frame_rate: 1.0 # Default: 1.0
  prior_noise: 1.0e-9 # Default: 1.0e-9
  
  # Note: no intrinsic noise provided in Euroc
  #cov_gyro_noise: 2.5e-05 # as per angular_velocity_covariance field in /imu/data
  #cov_accel_noise: 2.6e-07 # as per linear_acceleration_covariance field in /imu/data
  #cov_gyro_bias: 2.5e-05 # assume two orders of magnitude less than cov_gyro_noise
  #cov_accel_bias: 2.6e-08 # assume one order of magnitude less than cov_accel_noise
