## global parameters: These will be used in multiple locations

# optimization params
optimization_frequency: 1
lag_duration: 5

# frames
imu_frame: "imu"
lidar_frame: "velodyne"
camera_frame: "camera"
world_frame: "world"
baselink_frame: "camera"

# calibrations
static_extrinsics: true
camera_intrinsics_path: "/home/alex/catkin_ws/src/beam_slam/beam_slam_launch/calibrations/kaarta/camera.json"
imu_intrinsics_path: "/home/alex/catkin_ws/src/beam_slam/beam_slam_launch/calibrations/kaarta/imu.json"

## model plugins: declare all plugins to use and give a unique name
sensor_models:
  - name: 'imu_3d'
    type: 'beam_models::frame_to_frame::Imu3D'

motion_models:
  - name: 'unicycle_3d'
    type: 'beam_models::motion::Unicycle3D'

publishers:
  - name: 'odom_pub'
    type: 'beam_publishers::Odometry3DPublisher'
  - name: 'path_pub'
    type: 'beam_publishers::Path3DPublisher'    

solver_options:
  minimizer_type: "TRUST_REGION"
  linear_solver_type: "SPARSE_NORMAL_CHOLESKY"
  minimizer_progress_to_stdout: true
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 50
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

optimization_period: 1
lag_duration: 10

unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000

imu_3d:
  subscriber_topic: "/imu/data"
  sensor_frame: 'base_link'
  frame_initializer_type: 'ODOMETRY'
  frame_initializer_info: '/odometry/ground_truth'
  queue_size: 300 # Default: 300
  window_time: 1.00 # Default: 1.00
  prior_noise: 1.0e-9 # Default: 1.0e-9
  cov_gyro_noise: 0.02 # Required
  cov_accel_noise: 0.02 # Required
  cov_gyro_bias: 0.02 # Required
  cov_accel_bias: 0.02 # Required

path_pub:
  frame_id: 'odom' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # I DONT THINK THIS IS USED. Default: map
  odom_frame_id: 'odom' # I DONT THINK THIS IS USED. Default: odom
  base_link_frame_id: 'base_link' # I DONT THINK THIS IS USED. Default: base_link
  base_link_output_frame_id: 'base_link' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'odom' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: 'fixed_lag_smoother/optimized_odometry' # Output odometry topic
  