###################################
#    sensor model declarations    #
###################################
sensor_models:
# Initialization: 
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
# Front end:
  - name: 'visual_feature_tracker'
    type: 'bs_models::VisualFeatureTracker'
# Odometry's
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
  - name: 'visual_odometry'
    type: 'bs_models::VisualOdometry'

##############################
#    optimizer parameters    #
##############################
optimization_period: 1
lag_duration: 10

###########################
#    solver parameters    #
###########################
solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_SCHUR'
  minimizer_progress_to_stdout: true
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 8
  max_solver_time_in_seconds: 0.5
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015


#####################################
#     visual tracker parameters     #
#####################################
visual_feature_tracker:
  image_topic: '/F1/image_raw'
  descriptor_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/orb_descriptor.json'
  detector_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/fastssc_detector.json'
  tracker_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/tracker.json'
  save_tracks_folder: ""

slam_initialization:
  visual_measurement_topic: "/local_mapper/visual_feature_tracker/visual_measurements"
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_points"
  frame_initializer_config: "/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/frame_initializers/lvi_slam.json"
  init_mode: "VISUAL"
  max_optimization_s: 0.0
  max_container_size: 100
  min_parallax: 50.0
  min_trajectory_length_m: 1.0
  output_folder: ""

inertial_odometry:
  imu_topic: "/imu/data"
  constraint_odom_topic: "/local_mapper/visual_odometry/odom/relative"

visual_odometry:
  visual_measurement_topic: "/local_mapper/visual_feature_tracker/visual_measurements"
  max_container_size: 300
  frame_initializer_config: "/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/frame_initializers/io.json"
  frame_initializer_prior_noise_diagonal: [0,0,0,0,0,0]
  use_pose_priors: false
  reloc_request_period: 3.0
  keyframe_parallax: 10.0
  keyframe_translation_m: 2.0
  keyframe_rotation_deg: 20.0