###################################
#    sensor model declarations    #
###################################
sensor_models:
  - name: 'slam_initialization'
    type: 'bs_models::SLAMInitialization'
    ignition: true
  - name: 'visual_feature_tracker'
    type: 'bs_models::VisualFeatureTracker'
<<<<<<< HEAD
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
=======
>>>>>>> 78e473c6f41dff56b2f0f86e685fce0cb9065de5

##############################
#    optimizer parameters    #
##############################
optimization_period: 2
lag_duration: 10

###########################
#    solver parameters    #
###########################
solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_SCHUR'
  minimizer_progress_to_stdout: true
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 8
  max_solver_time_in_seconds: 0.5
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015


#####################################
#     visual tracker parameters     #
#####################################
visual_feature_tracker:
  image_topic: '/F1/image_raw'
  descriptor_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/orb_descriptor.json'
  detector_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/fastssc_detector.json'
  tracker_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/tracker.json'
  save_tracks_folder: "/userhome/results/tracks"

slam_initialization:
  visual_measurement_topic: "/local_mapper/visual_feature_tracker/visual_measurements"
  imu_topic: "/imu/data"
  lidar_topic: "/lidar_h/velodyne_points"
  frame_initializer_config: "/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/frame_initializers/lvi_slam.json"
  init_mode: "FRAMEINIT"
  max_optimization_s: 1.0
  max_container_size: 100
  min_parallax: 100.0
  min_trajectory_length_m: 1.0
  frame_init_frequency: 0.2
<<<<<<< HEAD
  output_folder: "/userhome/results/vo_init_results"

inertial_odometry:
  imu_topic: "/imu/data"
  constraint_odom_topic: ""
=======
  output_folder: "/userhome/results/vo_init_results"
>>>>>>> 78e473c6f41dff56b2f0f86e685fce0cb9065de5
