###################################
#    sensor model declarations    #
###################################
sensor_models:
  - name: 'lidar_aggregation'
    type: 'bs_models::LidarAggregation'  
  - name: 'gt_initializer'
    type: 'bs_models::GTInitializer'
  - name: 'inertial_odometry'
    type: 'bs_models::InertialOdometry'
    motion_models: ['unicycle_3d']
    ignition: true
  
###################################
#    motion model declarations    #
###################################
motion_models:
  - name: 'unicycle_3d'
    type: 'bs_models::Unicycle3D'

################################
#    publisher declarations    #
################################
# publishers:
#   - name: 'odom_pub'
#     type: 'bs_publishers::Odometry3DPublisher'
#   - name: 'path_pub'
#     type: 'bs_publishers::Path3DPublisher'

##############################
#    optimizer parameters    #
##############################
optimization_period: 1.0
lag_duration: 5
num_states: 10

###########################
#    solver parameters    #
###########################
solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_SCHUR'
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 0
  max_solver_time_in_seconds: 0.04
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

##################################
#     motion model parameters    #
##################################
unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000

##############################
#     odometry parameters    #
##############################
inertial_odometry:
  input_topic: '/imu/data'
  init_path_topic: '/local_mapper/gt_initializer/result'
  init_use_scale_estimate: false
  keyframe_rate: 0.1
  msg_queue_size: 10000

###################################
#     lidar aggregation params    #
###################################
lidar_aggregation:
  aggregation_time_topic: '/local_mapper/inertial_odometry/pose_stamps'
  odometry_topic: '/local_mapper/inertial_odometry/odometry'
  use_trigger: true
  pointcloud_topic: '/lidar_h/velodyne_packets_unpacked'
  max_aggregation_time_seconds: 0.1 

###################################
#   SLAM initializer parameters   #
###################################
gt_initializer:
  imu_topic: "/imu/data"
  frame_initializer_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/frame_initializers/vicon.json'
  trajectory_time_window: 5.0
  min_trajectory_length: 0.2 # trajectory length to accept (in metres)

############################
#   publisher parameters   #
############################
path_pub:
  frame_id: 'world' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # Default: map
  odom_frame_id: 'world' # Default: odom
  base_link_frame_id: 'imu' # Default: base_link
  base_link_output_frame_id: 'imu' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'world' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: '/local_mapper/optimized_odometry' # Output odometry topic