###################################
#    sensor model declarations    #
###################################
sensor_models:
  - name: 'visual_inertial_odometry'
    type: 'bs_models::VisualInertialOdometry'
    motion_models: ['unicycle_3d']
    ignition: true
  - name: 'vo_initializer'
    type: 'bs_models::VOInitializer'
  
###################################
#    motion model declarations    #
###################################
motion_models:
  - name: 'unicycle_3d'
    type: 'bs_models::Unicycle3D'

################################
#    publisher declarations    #
################################
# publishers:
#   - name: 'odom_pub'
#     type: 'bs_publishers::Odometry3DPublisher'
#   - name: 'path_pub'
#     type: 'bs_publishers::Path3DPublisher'

##############################
#    optimizer parameters    #
##############################
optimization_period: 0.5
lag_duration: 5
num_states: 15

###########################
#    solver parameters    #
###########################
solver_options:
  minimizer_type: 'TRUST_REGION'
  linear_solver_type: 'SPARSE_SCHUR'
  minimizer_progress_to_stdout: false
  num_threads: 6
  num_linear_solver_threads: 6
  max_num_iterations: 8
  max_solver_time_in_seconds: 0.04
  gradient_tolerance: 0.00000015
  parameter_tolerance: 0.00000015
  function_tolerance: 0.00000015

##################################
#     motion model parameters    #
##################################
unicycle_3d:
  process_noise_diagonal: [1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2,
                           1.0e-2, 1.0e-2, 1.0e-2]
  buffer_length: 100000

##############################
#     odometry parameters    #
##############################
visual_inertial_odometry:
  # topics to subscribe to
  image_topic: '/F1/image_mono/downscaled2'
  imu_topic: '/imu/data'
  init_path_topic: '/local_mapper/vo_initializer/result'
  # feature tracking configs
  descriptor: 'BEBLID'
  detector: 'FAST'
  descriptor_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/descriptor.json'
  detector_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/fast_detector.json'
  tracker_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/tracker.json'
  # keyframe decision params and memory management params
  tracker_window_size: 300 
  num_features_to_track: 100 
  keyframe_window_size: 20 
  keyframe_parallax: 10.0
  # initialization params
  init_max_optimization_time_in_seconds: 0.5
  init_map_output_directory: '' 
  init_use_scale_estimate: true

##############################
#   initializer parameters   #
##############################
vo_initializer:
  image_topic: '/F1/image_mono/downscaled'
  detector: 'FAST'
  detector_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/fast_detector.json'
  tracker_config: '/userhome/catkin_ws/src/beam_slam/beam_slam_launch/config/vio_config/tracker.json'
  parallax: 40.0
  tracker_window_size: 100

############################
#   publisher parameters   #
############################
path_pub:
  frame_id: 'world' # Stored in pose header. Default: odom
  path_topic: 'path' # Default: path
  pose_array_topic: 'pose_array' # Default: pose_array

odom_pub:
  publish_tf: false # Default: true
  predict_to_current_time: false # Default: false
  tf_publish_frequency: 10 # Default: 10
  tf_cache_time: 10 # Default: 10
  tf_timeout: 0.1 # Default: 0.1
  queue_size: 1 # Publisher queue size. Default: 1
  map_frame_id: 'map' # Default: map
  odom_frame_id: 'world' # Default: odom
  base_link_frame_id: 'imu' # Default: base_link
  base_link_output_frame_id: 'imu' # Stored in odometry.child_frame_id Default: base_link_frame_id
  world_frame_id: 'world' # Stored in odometry.header.frame_id. Default: odom_frame_id
  topic: '/local_mapper/optimized_odometry' # Output odometry topic